echo "------------------------------------------"
echo "Connected to $1 successfully!"
echo "------------------------------------------"
echo "--------------------"
echo "Manipulation Menu"
echo "--------------------"
echo "1) create table"
echo "2) list tables"
echo "3) drop table"
echo "4) insert into table"
echo "5) select from table"
echo "6) delete from table"
echo "7) update table"
echo "8) return to menu"
